### ISSUE TITLE
`my` and postderef?

### ISSUE THREAD

**Issue by cxw42** [jacoby/jacoby.github.io#1]
Dave, CXW here.  I read https://jacoby.github.io/perl/2018/08/28/how-i-write-perl-boilerplate-and-signatures.html and am wondering if you would be willing to expand on postderef.  Specifically, in https://jacoby.github.io/2019/03/18/more-fun-with-javascript-arrays-reimplementing-uniq.html , you blew my mind with:

    my $hedgehogs->@* = map { int rand 10 } 0..9;

I am familiar with `my @hedgehogs` and `my $hedgehogs=[]`, but the postderef form seems very strange to me!  It looks like dereferencing an `undef`, if I read it left to right.  I think it might be my clue to stop thinking about `my` as if it were a statement, but I'm not sure.  Would you be willing to provide some insight in a future blog post?  Thanks for considering this request!

**Edit** Is it related to [`refaliasing`](https://perldoc.perl.org/perlref.html#Assigning-to-References) or [`declared_refs`](https://perldoc.perl.org/perlref.html#Declaring-a-Reference-to-a-Variable)?

**Comment by jacoby** [comment]
I thought I commented on this last night but I'm not seeing this.

`my $hedgehogs->@* = ...` is equivalent to `my $hedgehogs = []; @$hedgehogs = ...`, with the indicator that we're working with a referenced array occurring after the variable and not before. 

I have never used `\$var` as a thing to be assigned to, and `refaliasing` is new to me. `declared_refs` is similarly new. `$var = []` or `$var = {}` or $var = sub {...}` has been sufficient for me. I'm going to have to look through and see what I think about those forms.

I went into some of [the details of the usage in a new blog post today](https://jacoby.github.io/2019/05/28/references-dereferences-and-perl.html). This **might** help, and even if it doesn't, it might help someone else.

**Comment by jacoby** [comment]
I'm gonna mark this closed unless you have further questions.

**Comment by cxw42** [comment]
Dave, thanks for the article and details, which I read and appreciated.  Based on your comments, I did a little more poking, which I will leave here for the benefit of future readers (or your own interest :) ).

Regular scalar assignment:

    $ perl -MO=Concise -E 'my $a = 1'
    6  <@> leave[1 ref] vKP/REFC ->(end)
    1     <0> enter ->2
    2     <;> nextstate(main 2 -e:1) v:%,us,{,fea=7 ->3
    5     <2> sassign vKS/2 ->6
    3        <$> const[IV 1] s ->4
    4        <0> padsv[$a:2,3] sRM*/LVINTRO ->5
    -e syntax OK

Postderef array assignment:

    $ perl -MO=Concise -E 'my $a->@* = 1'
    9  <@> leave[1 ref] vKP/REFC ->(end)
    1     <0> enter ->2
    2     <;> nextstate(main 2 -e:1) v:%,us,{,fea=7 ->3
    8     <2> aassign[t3] vKS ->9
    -        <1> ex-list lK ->5
    3           <0> pushmark s ->4
    4           <$> const[IV 1] s ->5
    -        <1> ex-list lK ->8
    5           <0> pushmark s ->6
    7           <1> rv2av[t2] lKRM*/1 ->8
    6              <0> padsv[$a:2,3] sM/LVINTRO,DREFAV ->7
    -e syntax OK
    
In the postderef case, `$a` gets the `DREFAV` private flag, and there's an `rv2av` op in the tree.  I looked for `rv2av` but didn't find much in perlguts, perlapi, or online.  I next looked at the private flag.

Per [`B::Concise`](https://metacpan.org/pod/B::Concise#OP-flags-abbreviations), the private flags are defined in "regen/op_private".  Turns out that file is a Perl source file.  `regen/op_private` [defines](https://github.com/Perl/perl5/blob/55b62dee2d8dffa7b36b3b613ee4727fbefdb9e3/regen/op_private#L398-L409) `DREFAV` as indicating:

> autovivify: Want ref to something

So the underlying mechanism is apparently autovivification, but of the thing on the left of the `->` rather than the thing on the right!  For additional data, I tried an example of classic autovivification:

    $ perl -MO=Concise -E 'my $a->[0] = 1'
    7  <@> leave[1 ref] vKP/REFC ->(end)
    1     <0> enter ->2
    2     <;> nextstate(main 2 -e:1) v:%,us,{,fea=7 ->3
    6     <2> sassign vKS/2 ->7
    3        <$> const[IV 1] s ->4
    -        <1> ex-aelem sKRM*/2 ->6
    5           <+> multideref(->[0]) sKM ->6
    -              <1> ex-rv2av sKR/1 ->5
    4                 <0> padsv[$a:2,3] sM/LVINTRO,DREFAV ->5
    -e syntax OK
    
`$a` also gets the `DREFAV` flag here, which is consistent with the postderef case.  

Ikegami posted [an explanation](https://www.perlmonks.org/?node_id=691609) in 2008: when an undefined scalar is used as a reference in an lvalue expression, the scalar is autovivified based on how it is used.  I knew autovivification worked within existing arrays or hashes, but I did not know until today that it created new arrays and hashes even without a parent array or hash.
