### ISSUE TITLE
“I Will Replace You With A Small Shell Script” notes

### ISSUE THREAD

**Issue by gizmomathboy** [jacoby/jacoby.github.io#11]
One small typo and one note

s/Earth/Universe/

I don't know when it got into bash but it has arrays

https://www.gnu.org/software/bash/manual/html_node/Arrays.html

I would assume most "modern" shells would (ksh, tcsh, zsh, fish, etc) but I haven't gone looking. I mostly just use bash.

That is all.

Good post regardless.

**Comment by jacoby** [comment]
Thanks.

I noticed a few other things and will get into it later today

--
Dave Jacoby

sent from my pocket supercomputer
