### ISSUE TITLE
Repeating values in list context

### ISSUE THREAD

**Issue by andrezgz** [jacoby/jacoby.github.io#2]
Hi Dave, I'm Andrezgz from the Perl Weekly Challenge.

Reading https://jacoby.github.io//2019/12/10/words-and-dates-which-is-more-fun.html I notice in your discussion points, the following one:

> I use a dose of clever to get an array of all the tiles. 'A' x 7 becomes AAAAAAA, and I join and split them. I suppose there’s a way to just pass the values in a way where I don’t get [ ['a','a','a','a','a','a','a','a'] , ['b','b','b','b','b'] ], and I should find it someday…

Reviewing your code:

`my @letters = split //, join '', map { $_ x $counts->{$_} } 'a' .. 'z';`

What do you think about this?:

`my @letters = map { ($_) x $counts->{$_} } 'a' .. 'z';`

The repetition operator in list context, with the left operand either enclosed in parentheses or a qw// list, performs a list repetition. In that case it supplies list context to the left operand, and returns a list consisting of the left operand list repeated the number of times specified by the right operand. From [perlop - Multiplicative Operators](https://perldoc.perl.org/perlop.html#Multiplicative-Operators)

Thanks for blogging about your code!

**Comment by jacoby** [comment]
It never occurred to me to use `x`be in list context. I like it. Thank you.

**Comment by andrezgz** [comment]
I've used it on my solution for this same task to create the array of available letters (tiles), too. Not as cool as your way but it does the trick :)

https://github.com/manwar/perlweeklychallenge-club/blob/master/challenge-038/andrezgz/perl5/ch-2.pl
