### ISSUE TITLE
Reviewing Challenge 56 Task 1

### ISSUE THREAD

**Issue by andrezgz** [jacoby/jacoby.github.io#5]
Hi, Dave!

I was reading the first task detail on https://jacoby.github.io//2020/04/13/challenge-56-diffk-and-binary-trees.html and I think the line
`next if $i == $j;`
is unnecessary because the way the nested loops were coded, it will never be true.

The whole solution is so simple that removing that line will make it more precise :)

**Comment by jacoby** [comment]
That's reasonable. I'll get to it after work.
