### ISSUE TITLE
2020-06-30 regex post pipe rendering

### ISSUE THREAD

**Issue by gizmomathboy** [jacoby/jacoby.github.io#7]
There is something weird going on with (bat|pl) throughout the post.

It sometimes renders ok, others...not so much.

Not sure what needs to be done in the markdown to fix that.

**Comment by gizmomathboy** [comment]
Might have to use an html entity maybe. The markdown thinks  you want a table.

https://stackoverflow.com/questions/17319940/how-to-escape-a-pipe-char-in-a-code-statement-in-a-markdown-table

**Comment by jacoby** [comment]
VS Code markdown had no problem with that. 

Thanks.
