### ISSUE TITLE
Who is still disabling js?

### ISSUE THREAD

**Issue by vybeauregard** [jacoby/jacoby.github.io#9]
I don’t have numbers to back it up, but practically speaking, how is the Internet in 2021 even slightly useful to anyone with js disabled?

there may be one hyper nerd browsing to your calendar via command line but if it’s me? I say use the technology stack that makes updating it as frictionless as possible.

**Comment by vybeauregard** [comment]
I can say as a web dev for a ton of researchers, all of our apps depend on js (increasingly vuejs) and I’ve not received a single report of failure due to disabled js.

**Comment by jacoby** [comment]
I know that @gizmomathboy blocklists everything and allowlists things as needed.

**Comment by gizmomathboy** [comment]
Yep, noscript runs and I don't have anything in the allowlist...I think.

mostly to kill tracking and ads and such.

Yes it is a huge pain in the ass to give temporary permission to the js that is needed. Of course I also fire up chrome to deal with sites that make it a pain to figure out which js is "needed" and such but I try to keep that to a minimum.

**Comment by gizmomathboy** [comment]
That all being said, as Dave rightly points out, if meetup goes down...there is a team of folks having a bad day and trying to get it back online.

Which is a long way to day, I'm fine with using js and api.meetup to make some parts easier, or maybe more interesting for the dev team ;-)

It's enhanced functionality/window dressing that isn't downloading 5MB of ad/tracking libraries.

I might be a neo-luddite but I'm not that much of a neo-luddite :-)
